version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - CLIENT_URL=http://localhost:5000
    volumes:
      - ./uploads:/app/server/uploads
    restart: unless-stopped