[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
  "cd server && npm ci",
  "cd ../client && npm ci"
]

[phases.build]
cmds = [
  "cd server && npm run build",
  "cd ../client && npm run build",
  "cp -r ../client/dist ../server/public"
]

[start]
cmd = "cd server && node dist/index.js"